In [2]:
import pandas as pd

df = pd.read_csv("../data/extra/2_prepro_차량등록현황.csv",encoding = "cp949")
df

,구 분,합계(용도별),관용,자가용,영업용,합계(차종별),승용,승합,화물,특수
0,고기동,2040.0,-,2034.0,6,2040.0,1817.0,52.0,162.0,9.0
1,고림동,12176.0,-,11740.0,436,12176.0,10229.0,388.0,1496.0,63.0
2,고매동,3038.0,-,2787.0,251,3038.0,2302.0,217.0,505.0,14.0
3,공세동,8026.0,-,7807.0,219,8026.0,7096.0,169.0,743.0,18.0
4,구갈동,18577.0,1,17193.0,1383,18577.0,16726.0,383.0,1417.0,51.0
5,기흥구,200001.0,123,192924.0,6954,200001.0,179619.0,4518.0,15265.0,599.0
6,김량장동,9391.0,25,9063.0,303,9391.0,7908.0,357.0,1090.0,36.0
7,남동,3786.0,-,3054.0,732,3786.0,2578.0,763.0,437.0,8.0
8,남사읍,13761.0,28,13478.0,255,13761.0,11151.0,355.0,2198.0,57.0
9,농서동,2132.0,-,1968.0,164,2132.0,1724.0,81.0,312.0,15.0
10,동백동,15565.0,1,15368.0,196,15565.0,14400.0,282.0,842.0,41.0
11,동천동,20210.0,1,19448.0,761,20210.0,18468.0,255.0,1450.0,37.0
12,마북동,13347.0,5,13124.0,218,13347.0,12449.0,233.0,644.0,21.0
13,마평동,5706.0,-,5445.0,261,5706.0,4526.0,213.0,912.0,55.0
14,모현읍,16440.0,-,15569.0,871,16440.0,12142.0,731.0,3502.0,65.0
15,백암면,6482.0,1,5218.0,1263,6482.0,3613.0,256.0,2453.0,160.0
16,보라동,12559.0,-,12128.0,431,12559.0,11168.0,285.0,1073.0,33.0
17,보정동,16469.0,48,15698.0,723,16469.0,15195.0,435.0,815.0,24.0
18,삼가동,6642.0,634,5777.0,231,6642.0,5655.0,300.0,658.0,29.0
19,상갈동,5403.0,-,5252.0,151,5403.0,4771.0,132.0,489.0,11.0
20,상하동,11100.0,-,10794.0,306,11100.0,9720.0,274.0,1080.0,26.0
21,상현동,32294.0,2,31824.0,468,32294.0,30530.0,500.0,1220.0,44.0
22,서천동,9259.0,-,8963.0,296,9259.0,8590.0,231.0,416.0,22.0
23,성복동,22716.0,-,22670.0,46,22716.0,21747.0,276.0,650.0,43.0
24,수지구,151162.0,59,148687.0,2416,151162.0,142311.0,2273.0,6343.0,235.0
25,신갈동,16435.0,45,15817.0,573,16435.0,14466.0,388.0,1514.0,67.0
26,신봉동,16713.0,-,16517.0,196,16713.0,15899.0,249.0,531.0,34.0
27,양지면,12943.0,-,11944.0,999,12943.0,9712.0,414.0,2699.0,118.0
28,언남동,10068.0,4,9698.0,366,10068.0,9203.0,166.0,680.0,19.0
29,역북동,14173.0,85,13754.0,334,14173.0,12555.0,340.0,1216.0,62.0
30,영덕동,24547.0,4,24159.0,384,24547.0,22416.0,417.0,1650.0,64.0
31,운학동,857.0,1,834.0,22,857.0,614.0,28.0,199.0,16.0
32,원삼면,5869.0,2,5358.0,509,5869.0,3974.0,147.0,1709.0,39.0
33,유방동,6107.0,-,5810.0,297,6107.0,4861.0,212.0,897.0,137.0
34,이동읍,13071.0,11,12100.0,960,13071.0,9520.0,386.0,3119.0,46.0
35,죽전동,28411.0,31,27935.0,445,28411.0,26723.0,536.0,1122.0,30.0
36,중동,20710.0,-,20285.0,425,20710.0,18948.0,400.0,1285.0,77.0
37,지곡동,2706.0,-,2509.0,197,2706.0,2046.0,129.0,492.0,39.0
38,처인구,145992.0,797,137077.0,8118,145992.0,113491.0,5638.0,25838.0,1025.0
39,청덕동,7059.0,15,6825.0,219,7059.0,6177.0,215.0,638.0,29.0
40,포곡읍,18018.0,10,17364.0,644,18018.0,14033.0,733.0,3123.0,129.0
41,풍덕천동,28778.0,25,28259.0,494,28778.0,27127.0,405.0,1208.0,38.0
42,하갈동,3001.0,-,2549.0,452,3001.0,2222.0,81.0,670.0,28.0
43,해곡동,174.0,-,174.0,-,174.0,112.0,6.0,55.0,1.0
44,호동,396.0,-,395.0,1,396.0,308.0,9.0,75.0,4.0
45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df.sort_values(by= "합계(용도별)",ascending = False)

,구 분,합계(용도별),관용,자가용,영업용,합계(차종별),승용,승합,화물,특수
5,기흥구,200001.0,123,192924.0,6954,200001.0,179619.0,4518.0,15265.0,599.0
24,수지구,151162.0,59,148687.0,2416,151162.0,142311.0,2273.0,6343.0,235.0
38,처인구,145992.0,797,137077.0,8118,145992.0,113491.0,5638.0,25838.0,1025.0
21,상현동,32294.0,2,31824.0,468,32294.0,30530.0,500.0,1220.0,44.0
41,풍덕천동,28778.0,25,28259.0,494,28778.0,27127.0,405.0,1208.0,38.0
35,죽전동,28411.0,31,27935.0,445,28411.0,26723.0,536.0,1122.0,30.0
30,영덕동,24547.0,4,24159.0,384,24547.0,22416.0,417.0,1650.0,64.0
23,성복동,22716.0,-,22670.0,46,22716.0,21747.0,276.0,650.0,43.0
36,중동,20710.0,-,20285.0,425,20710.0,18948.0,400.0,1285.0,77.0
11,동천동,20210.0,1,19448.0,761,20210.0,18468.0,255.0,1450.0,37.0
4,구갈동,18577.0,1,17193.0,1383,18577.0,16726.0,383.0,1417.0,51.0
40,포곡읍,18018.0,10,17364.0,644,18018.0,14033.0,733.0,3123.0,129.0
26,신봉동,16713.0,-,16517.0,196,16713.0,15899.0,249.0,531.0,34.0
17,보정동,16469.0,48,15698.0,723,16469.0,15195.0,435.0,815.0,24.0
14,모현읍,16440.0,-,15569.0,871,16440.0,12142.0,731.0,3502.0,65.0
25,신갈동,16435.0,45,15817.0,573,16435.0,14466.0,388.0,1514.0,67.0
10,동백동,15565.0,1,15368.0,196,15565.0,14400.0,282.0,842.0,41.0
29,역북동,14173.0,85,13754.0,334,14173.0,12555.0,340.0,1216.0,62.0
8,남사읍,13761.0,28,13478.0,255,13761.0,11151.0,355.0,2198.0,57.0
12,마북동,13347.0,5,13124.0,218,13347.0,12449.0,233.0,644.0,21.0
34,이동읍,13071.0,11,12100.0,960,13071.0,9520.0,386.0,3119.0,46.0
27,양지면,12943.0,-,11944.0,999,12943.0,9712.0,414.0,2699.0,118.0
16,보라동,12559.0,-,12128.0,431,12559.0,11168.0,285.0,1073.0,33.0
1,고림동,12176.0,-,11740.0,436,12176.0,10229.0,388.0,1496.0,63.0
20,상하동,11100.0,-,10794.0,306,11100.0,9720.0,274.0,1080.0,26.0
28,언남동,10068.0,4,9698.0,366,10068.0,9203.0,166.0,680.0,19.0
6,김량장동,9391.0,25,9063.0,303,9391.0,7908.0,357.0,1090.0,36.0
22,서천동,9259.0,-,8963.0,296,9259.0,8590.0,231.0,416.0,22.0
3,공세동,8026.0,-,7807.0,219,8026.0,7096.0,169.0,743.0,18.0
39,청덕동,7059.0,15,6825.0,219,7059.0,6177.0,215.0,638.0,29.0
18,삼가동,6642.0,634,5777.0,231,6642.0,5655.0,300.0,658.0,29.0
15,백암면,6482.0,1,5218.0,1263,6482.0,3613.0,256.0,2453.0,160.0
33,유방동,6107.0,-,5810.0,297,6107.0,4861.0,212.0,897.0,137.0
32,원삼면,5869.0,2,5358.0,509,5869.0,3974.0,147.0,1709.0,39.0
13,마평동,5706.0,-,5445.0,261,5706.0,4526.0,213.0,912.0,55.0
19,상갈동,5403.0,-,5252.0,151,5403.0,4771.0,132.0,489.0,11.0
7,남동,3786.0,-,3054.0,732,3786.0,2578.0,763.0,437.0,8.0
2,고매동,3038.0,-,2787.0,251,3038.0,2302.0,217.0,505.0,14.0
42,하갈동,3001.0,-,2549.0,452,3001.0,2222.0,81.0,670.0,28.0
37,지곡동,2706.0,-,2509.0,197,2706.0,2046.0,129.0,492.0,39.0
9,농서동,2132.0,-,1968.0,164,2132.0,1724.0,81.0,312.0,15.0
0,고기동,2040.0,-,2034.0,6,2040.0,1817.0,52.0,162.0,9.0
31,운학동,857.0,1,834.0,22,857.0,614.0,28.0,199.0,16.0
44,호동,396.0,-,395.0,1,396.0,308.0,9.0,75.0,4.0
43,해곡동,174.0,-,174.0,-,174.0,112.0,6.0,55.0,1.0
45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4141 entries, 0 to 4140
Data columns (total 22 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   statNm       4141 non-null   object
 1   statId       4141 non-null   object
 2   chgerId      4141 non-null   int64
 3   chgerType    4141 non-null   int64
 4   addr         4137 non-null   object
 5   lat          4141 non-null   float64
 6   lng          4141 non-null   float64
 7   useTime      4011 non-null   object
 8   busiId       4141 non-null   object
 9   bnm          4141 non-null   object
 10  busiNm       4141 non-null   object
 11  stat         4141 non-null   int64
 12  statUpdDt    4032 non-null   float64
 13  output       2608 non-null   float64
 14  method       2723 non-null   object
 15  zcode        4141 non-null   int64
 16  zscode       4141 non-null   int64
 17  limitYn      4141 non-null   object
 18  delYn        4141 non-null   object
 19  kindDetail   4122 non-null   object
 20  parkingFree  4131 non-null   object
 21  note         905 non-null    object
dtypes: float64(4), int64(5), object(13)
memory usage: 711.9+ KB

In [10]:
## useTime value
df.useTime.value_counts()

24시간 이용가능                             2792
24시간 이용가능,입주민만 사용가능 거주자외출입제한           448
09:00~18:00                            347
08:00~22:00                             67
24시간                                    49
08:00~20:00                             48
24시간 이용가능/외부인 출입제한                      42
~                                       38
평일 09:00~18:00                          30
10:00~22:00                             23
24시간 이용가능/시설 상황에 따라 이용이 제한될 수 있습니다      19
평일 09시~18시 이용가능                         17
24시간 이용가능,입주민만 사용가능 거주자 외 출입제한          13
10:00~23:00                             12
주중/주말 : 06시~23시                          8
06:00~24:00                              7
주중/주말 : 00시~24시                          7
10:00:00~23:59:59                        6
점포영업시간                                   6
외부인 사용불가                                 5
07:30~19:00                              4
10:00:00~23:00:59                        4
10:00 ~ 23:00                            4
09:00~19:00                              4
24시간 이용가능(입주민 외 이용불가)                    2
00:00~23:59                              2
주중/주말 : 09시~18시                          1
07:00-22:00                              1
09:00~20:00                              1
08:30 ~ 17:30                            1
10:00~21:00                              1
24시간 이용가능(외부인 출입제한)                      1
07:00~22:00                              1
Name: useTime, dtype: int64

In [8]:
## busiId value
df.busiId.value_counts()

EV    834
PW    765
HM    458
PI    410
SF    312
GN    268
KP    210
EP    168
PL    149
HE    123
KL     75
ST     74
ME     43
KE     43
EZ     42
CU     38
CV     36
TD     16
JE     15
MO     14
NT     14
EC     12
SS     11
JA      3
LH      2
GS      2
CS      1
OB      1
HS      1
EM      1
Name: busiId, dtype: int64

In [9]:
## bnm value
df.bnm.value_counts()

에버온               834
파워큐브              765
휴맥스이브이            458
차지비               410
스타코프              312
지커넥트              241
한국전력공사            210
이카플러그             168
플러그링크             149
한국전기차충전서비스        123
클린일렉스              75
에스트래픽              74
환경부                43
한국전기차인프라기술         43
차지인                42
씨어스                38
대영채비               36
지에스커넥트             27
타디스테크놀로지           16
제주전기자동차서비스         15
매니지온               14
한국전자금융             14
이지차저               12
삼성EVC              11
중앙제어                3
LG헬로비전              2
GS칼텍스               2
현대오일뱅크              1
한국EV충전서비스센터         1
홈앤서비스               1
evMost(현대오일뱅크)      1
Name: bnm, dtype: int64

In [12]:
## stat value
df.stat.value_counts()

2    3012
9     449
1     343
3     271
4      51
5      15
Name: stat, dtype: int64

In [13]:
## sstatUpdDt value
df.statUpdDt.value_counts()

2.022090e+13    57
2.022092e+13    56
2.022092e+13    33
2.021122e+13    28
2.022092e+13    26
                ..
2.022091e+13     1
2.022092e+13     1
2.022092e+13     1
2.022092e+13     1
2.022092e+13     1
Name: statUpdDt, Length: 2508, dtype: int64

In [14]:
## output
df.output.value_counts()

7.0      2019
3.0       457
100.0      62
50.0       61
200.0       6
350.0       2
14.0        1
Name: output, dtype: int64

In [15]:
## method
df.method.value_counts()

단독    2601
동시     122
Name: method, dtype: int64

In [16]:
df.zscode.value_counts()

41460    4141
Name: zscode, dtype: int64

In [17]:
## kindDetail 충전소 구분코드 상세
df.kindDetail.value_counts()

H001    3433
H003     123
G004     120
E001      66
J001      48
A002      42
G005      30
A001      26
A003      26
E003      22
E004      21
F001      14
B004      13
C001      12
D008      11
B001       9
E006       9
I001       9
A004       8
D003       8
H002       7
E002       7
B002       7
I002       7
J007       6
E007       6
J005       6
I005       5
G006       4
J002       4
I004       3
D007       3
F002       3
E005       2
C002       1
D001       1
Name: kindDetail, dtype: int64

In [18]:
df.limitYn.value_counts()

N    2116
Y    2025
Name: limitYn, dtype: int64

In [19]:
## del 
df.delYn.value_counts()

N    4141
Name: delYn, dtype: int64

In [21]:
## parkingFree
df.parkingFree.value_counts()

Y    3143
N     988
Name: parkingFree, dtype: int64

In [22]:
## note
df.note.value_counts()

외부인 사용불가                          344
입주민만 사용가능 거주자 외 출입제한              209
입주민만 사용가능 거주자외 출입제한               203
입주민 등 거주자 외 출입 제한                  45
입주민 외 사용불가                         24
공동주택 입주민 전용                        22
입주자 외 사용불가                         16
입장 관람객 전용                           9
입주민만이용가능                            8
숙박시 무료                              6
점포영업시간                              6
방문등록 후 이용가능                         5
입주민전용                               2
실제 주소는 경기도 용인시 처인구 원삼면 좌전로 142      2
2015년 설치                            1
업무용 빌딩 입주자 대상 개방                    1
주차비1시간1500원                         1
주차비1시간1000원                         1
Name: note, dtype: int64

In [23]:
## 전처리, 필요없는 변수 제거

df_1 = df.drop(["busiId","bnm","busiNm","statUpdDt","zcode","zscode","delYn","note"],axis = 1)
df_1.head(3).T

,0,1,2
statNm,용인시청,포곡읍사무소,죽전휴게소(서울방향)
statId,ME174147,ME174148,ME178002
chgerId,1,1,1
chgerType,6,6,6
addr,경기도 용인시 처인구 삼가동 556,경기도 용인시 처인구 포곡읍 포곡로 258,경기도 용인시 수지구 경부고속도로 400 (죽전동)
lat,37.240666,37.2781,37.332073
lng,127.177375,127.231259,127.104848
useTime,24시간 이용가능,24시간 이용가능,24시간 이용가능
stat,2,9,3
output,50.0,50.0,50.0
method,단독,단독,단독
limitYn,N,N,N
kindDetail,A001,A002,C001
parkingFree,N,N,Y

In [24]:
df_1.to_csv("../data/extra/prepro_전기차충전소.csv",index = False, encoding = "cp949")